"""add time field to Habit

Revision ID: b4ee843f45aa
Revises: 0a1c104fd02e
Create Date: 2025-08-27 14:17:49.924199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ee843f45aa'
down_revision: Union[str, None] = '0a1c104fd02e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('time', sa.Time(), nullable=False, server_default='00:00:00'))
    op.alter_column('habits', 'time', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'time')
    # ### end Alembic commands ###
